#!/bin/sh
set -e

DOMAIN="${1:-}"

if [ -z "$DOMAIN" ]; then
    printf "Enter your domain (e.g., fuiz.example.com) or 'localhost' for local dev: "
    read -r DOMAIN
fi

if [ "$DOMAIN" = "localhost" ]; then
    SCHEME="https"
    WS_SCHEME="wss"
    DISPLAY_URL="localhost"
    FULL_URL="http://localhost"
else
    SCHEME="https"
    WS_SCHEME="wss"
    DISPLAY_URL="$DOMAIN"
    FULL_URL="https://$DOMAIN"
fi

cat > .env <<EOF
# Generated by generate_config.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Domain configuration
FUIZ_DOMAIN=$DOMAIN

# Frontend environment variables
ORIGIN=$FULL_URL
PUBLIC_DISPLAY_PLAY_URL=$DISPLAY_URL
PUBLIC_PLAY_URL=$FULL_URL
PUBLIC_BACKEND_URL=$FULL_URL/api
PUBLIC_WS_URL=$WS_SCHEME://$DOMAIN/api
PUBLIC_CORKBOARD_URL=$FULL_URL/corkboard

# Game server CORS
FUIZ_ALLOWED_ORIGINS=["$FULL_URL"]

# Corkboard CORS
CORKBOARD_ALLOWED_ORIGINS=["$FULL_URL"]

# AI configuration (optional)
# Uncomment and configure to enable AI-powered tag derivation for library quizzes
# Supports any OpenAI-compatible API (OpenAI, Ollama, OpenRouter, LiteLLM, etc.)
# OPENAI_BASE_URL=http://localhost:11434/v1
# OPENAI_API_KEY=
# AI_MODEL=gpt-4o-mini
EOF

echo "Configuration written to .env"
echo ""
echo "To start Fuiz, run:"
echo "  docker compose up -d"
